table Dim_Date
	lineageTag: 4a6c9b1e-2f3a-4d7e-9b6a-1c8d5e0f2a3b

	column Date
		lineageTag: 7e2d4f6a-8b1c-4a3d-9e5f-2c6a8b0d1e4f
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		isKey
		sourceColumn: Date

	column Year
		lineageTag: 1b3c5d7e-9f0a-4b2c-8d4e-6f8a0b2c4d6e
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: Year

	column Quarter
		lineageTag: 2c4d6e8f-0a1b-4c3d-9e5f-7a9b1c3d5e7f
		dataType: string
		summarizeBy: none
		sourceColumn: Quarter

	column QuarterSort
		lineageTag: 3d5e7f9a-1b2c-4d4e-0f6a-8b0c2d4e6f80
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: QuarterSort

	column MonthName
		lineageTag: 4e6f8a0b-2c3d-4e5f-1a7b-9c1d3e5f7a91
		dataType: string
		summarizeBy: none
		sortByColumn: MonthYearSort
		sourceColumn: MonthName

	column MonthShort
		lineageTag: 5f7a9b1c-3d4e-4f6a-2b8c-0d2e4f6a8ba2
		dataType: string
		summarizeBy: none
		sortByColumn: MonthYearSort
		sourceColumn: MonthShort

	column MonthYear
		lineageTag: 6a8b0c2d-4e5f-406a-3c9d-1e3f5a7b9cb3
		dataType: string
		summarizeBy: none
		sortByColumn: MonthYearSort
		sourceColumn: MonthYear

	column MonthYearSort
		lineageTag: 7b9c1d3e-5f60-417a-4d0e-2f406a8b0cc4
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: MonthYearSort

	column DayName
		lineageTag: 8c0d2e4f-6071-428b-5e1f-30517b9c1dd5
		dataType: string
		summarizeBy: none
		sortByColumn: WeekdayNum
		sourceColumn: DayName

	column WeekdayNum
		lineageTag: 9d1e3f50-7182-439c-6f20-41628c0d2ee6
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: WeekdayNum

	partition Dim_Date = m
		lineageTag: 0e2f4061-8293-440d-7031-52739d1e3ff7
		mode: import
		source =
				let
				    StartDate = #date(2025, 1, 1),
				    EndDate = #date(2027, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    Dates = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    Source = Table.FromList(Dates, Splitter.SplitByNothing(), {"Date"}),
				    ChangedType = Table.TransformColumnTypes(Source, {{"Date", type date}}),
				    AddYear = Table.AddColumn(ChangedType, "Year", each Date.Year([Date]), Int64.Type),
				    AddQuarter = Table.AddColumn(AddYear, "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date])) & " " & Text.From(Date.Year([Date])), type text),
				    AddQuarterSort = Table.AddColumn(AddQuarter, "QuarterSort", each Date.Year([Date]) * 10 + Date.QuarterOfYear([Date]), Int64.Type),
				    AddMonthName = Table.AddColumn(AddQuarterSort, "MonthName", each Date.MonthName([Date]), type text),
				    AddMonthShort = Table.AddColumn(AddMonthName, "MonthShort", each Text.Start(Date.MonthName([Date]), 3), type text),
				    AddMonthYear = Table.AddColumn(AddMonthShort, "MonthYear", each Text.Start(Date.MonthName([Date]), 3) & " " & Text.From(Date.Year([Date])), type text),
				    AddMonthYearSort = Table.AddColumn(AddMonthYear, "MonthYearSort", each Date.Year([Date]) * 100 + Date.Month([Date]), Int64.Type),
				    AddDayName = Table.AddColumn(AddMonthYearSort, "DayName", each Date.DayOfWeekName([Date]), type text),
				    AddWeekdayNum = Table.AddColumn(AddDayName, "WeekdayNum", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    ChangedType2 = Table.TransformColumnTypes(AddWeekdayNum, {{"Date", type datetime}})
				in
				    ChangedType2

	annotation PBI_Id = Dim_Date
